baseURL = 'https://tungbach12.github.io/SmartDroneInspection-Docs/'
languageCode = 'en-us'
title = 'SmartDroneInspection Architecture Documentation'
theme = 'hugo-book'

[params]
  BookRepo = 'https://github.com/tungbach12/SmartDroneInspection-Docs'
  BookEditPath = 'edit/main/docs'
  BookSection = '*'
  BookLogo = false
